### ISSUE TITLE
KeyError: 'van_tiny is not in the models registry'

### ISSUE THREAD

**Issue by Shawn207** [Gsunshine/Enjoy-Hamburger#5]
Hi there,
I set up environment on docker with torch=1.11.0, cuda=11.3, mmcv-full=1.5.0. When I ran the code, I got this trace back info shown in picture
![error](https://user-images.githubusercontent.com/60746163/165371810-4742b2cf-a408-473f-95d1-33f13a3f633a.PNG)
the "hamenet_light_van_tiny_512x1024_160k_cityscapes.py" is the config file modified by myself based on ade20k one. The error msg seems to be unrelated with data, so it shouldn't be a problem.
Could you please give me any suggestion?
Thanks!

**Comment by Gsunshine** [comment]
Hi! Thank you for being so interested in the Hamburger! I guess that you need to `import van` in your `train/test.py` file to register the VAN backbone. For example, you may use the `/seg_light_ham/dist_test.sh` instead of the script under the `/tools/` directory because this command applies to the correct  `train/test.py` portal.

BTW, you can deploy the Light-Ham (VAN-Base) model. This one balances efficiency and performance very well.

Please feel free to ping me if you have additional questions!

**Comment by Shawn207** [comment]
Thank you! 
One more question: The batch size I inputed should be one, but when I was checking the data, there is actually 12 images batched together. Do you know where is the setting for that?
By the way, do you have model pretrained on cityscapes?

**Comment by Gsunshine** [comment]
Hi! I am not sure about the test batch size. The test batch size may be related to the number of GPUs you use because it is actually DistributedDataParallel (bs 1 per GPU to enable multi-GPU MSFlip test). Perhaps you can try to use one GPU only.

Good question. I only have pretrained checkpoints on ADE20K because some computing got expired. The good news here is that one of my collaborators will release a new paper regarding the power of VAN+Ham on segmentation. You may expect this paper.

Thanks!

**Comment by Shawn207** [comment]
Thank you!
