### ISSUE TITLE
缺少主干网络

### ISSUE THREAD

**Issue by m828** [Gsunshine/Enjoy-Hamburger#6]
源码中没有VAN 主干网络吗==！什么时候加上呢，期待

**Comment by m828** [comment]
我看到了van.py，但是train的时候仍然提示EncoderDecoder: 'van_base is not in the models registry'，请问该如何解决

**Comment by Gsunshine** [comment]
hi @m828 ,

有的哦，在[van.py](https://github.com/Gsunshine/Enjoy-Hamburger/blob/main/seg_light_ham/van.py)里面。[seg_light_ham](https://github.com/Gsunshine/Enjoy-Hamburger/tree/main/seg_light_ham)是一个直接可以跑+evaluate的code base，可以直接用`bash dist_train.sh /path/to/config 8`运行。dist_train.sh用的是最外面的[seg_light_ham/train.py](https://github.com/Gsunshine/Enjoy-Hamburger/blob/main/seg_light_ham/train.py)，已经包含了van的registration。而tools下面的train.py是没有import van的，用那个入口的话会出现这个error。

MMSeg是在train.py里面import对应的文件就会register。如果是在你自己的trainer里面运行，可以直接在开头import van。Ham也是一样的原理，head已经被注册在[seg_light_ham/mmseg/models/decode_heads/ham_head.py](https://github.com/Gsunshine/Enjoy-Hamburger/blob/main/seg_light_ham/mmseg/models/decode_heads/ham_head.py)里面了。

----

English reference for others who meet similar problems:

The VAN backbone has already been registered in [seg_light_ham/train.py](https://github.com/Gsunshine/Enjoy-Hamburger/blob/main/seg_light_ham/train.py). You should use the entry in [dist_train.sh](https://github.com/Gsunshine/Enjoy-Hamburger/blob/main/seg_light_ham/dist_train.sh) instead of [tools/train.py](https://github.com/Gsunshine/Enjoy-Hamburger/blob/main/seg_light_ham/tools/train.py), as the latter has no backbone registration. Simply run `bash dist_train.sh /path/to/config 8` to start your training. 

Similarly, for LightHam, you can also employ this head in your code base by registering it via `import ham_head`.

Please feel free to ask more questions if you have any. Enjoy Hamburger, please!
